SEARCHSPACE:
  NAME: DARTS
SEARCHSTRATEGY:
  NAME: DARTSAER
  DATASET: CIFAR10 # DARTS
  DATAPATH: datasets/cifar10 # DARTS
  INPUTSIZE: 32 # DARTS
  CUTOUT: 0 # AutoFormer | OFA | DARTS
  BATCHSIZE: 64 # DARTS default: 64
  WEIGHTLR: 0.025 # DARTS
  WEIGHTMOMENTUM: 0.9 # DARTS
  WEIGHTWEIGHTDECAY: 3e-4 # DARTS
  WEIGHTGRADCLIP: 5. # DARTS
  ALPHALR: 3e-4 # DARTS
  ALPHABETA1: 0.5 # DARTS
  ALPHABETA2: 0.999 # DARTS
  ALPHAWEIGHTDECAY: 1e-3 # DARTS
  EPOCHS: 3 # DARTS default: 50
  MINWEIGHTLR: 0.001 # DARTS
ESTIMATIONSTRATEGY:
  NAME: DARTS
  BATCHSIZE: 96 # AutoFormer | OFA | DARTS default: 64
  DATASET: CIFAR10 # AutoFormer | OFA | DARTS
  DATAPATH: datasets/cifar10 # AutoFormer | OFA | DARTS
  INPUTSIZE: 32 # AutoFormer | OFA | DARTS
  COLORJITTER: null # AutoFormer | OFA | DARTS
  AA: null # AutoFormer | OFA | DARTS
  TRAIN_INTERPOLATION: null # AutoFormer | OFA | DARTS
  REPROB: 0. # AutoFormer | OFA | DARTS
  REMODE: null # AutoFormer | OFA | DARTS
  RECOUNT: null # AutoFormer | OFA | DARTS
  CUTOUT: 16 # AutoFormer | OFA | DARTS
  AUXWEIGHT: 0.4 # DARTS
  LR: 0.025 # DARTS
  MOMENTUM: 0.9 # DARTS
  WEIGHTDECAY: 3e-4 # DARTS
  EPOCHS: 3 # DARTS default: 600
  DROPPATHPROB: 0.2 # DARTS
  GRAD_CLIP: 5. # DARTS
  EVALMODE: 'supernet' # DARTS
OUTPUT: output
TAG: test