SEARCHSPACE:
  NAME: DARTS
SEARCHSTRATEGY:
  NAME: PredictorBasedRandom
  PREDICTOR: GMAEPredictor # PredictorBasedRandom
  N: 100 # Random | AgingEvolution | PredictorBasedRandom default: 1000 | 100
  PATIENCEFACTOR: 5 # AgingEvolution | PredictorBasedRandom
  EPOCHS: 2 # DARTS | PredictorBasedRandom default: 25
  NUMLAYERS: 12 # PredictorBasedRandom
  MODELDIM: 32 # PredictorBasedRandom
  ACT: 'nn.PReLU()' # PredictorBasedRandom
  BASEMODEL: 'GATConv' # PredictorBasedRandom
  GRAPHENCDROPOUT: 0.0 # PredictorBasedRandom
  DROPOUT: 0.5 # PredictorBasedRandom
  PROJLAYERS: 64 # PredictorBasedRandom
  FIXEDENCODER: False # PredictorBasedRandom
  LR: 0.001 # PredictorBasedRandom
  ENCODERLR: 0.001 # PredictorBasedRandom
  WEIGHTDECAY: 0.01 # PredictorBasedRandom
  EXPWEIGHTED: False # PredictorBasedRandom
  OPTMODE: 'D' # PredictorBasedRandom
  OPTRESERVEP: 1.0 # PredictorBasedRandom
  NUMINITARCHS: 20 # PredictorBasedRandom default: 20
  NUMCANDS: 100 # PredictorBasedRandom default: 100
  K: 10 # PredictorBasedRandom default: 10
  # ENCODERSTATEDICT: 'model_ckpts/GMAENAS/pretrained_encoder.pt' # PredictorBasedRandom
  ENCODERSTATEDICT: null # PredictorBasedRandom
  PREDICTORSTATEDICT: null # PredictorBasedRandom
ESTIMATIONSTRATEGY:
  NAME: StandardTraining
  BATCHSIZE: 96 # AutoFormer | OFA | DARTS | StandardTraining default: 64
  DATASET: CIFAR10 # AutoFormer | OFA | DARTS | StandardTraining
  DATAPATH: datasets/cifar10 # AutoFormer | OFA | DARTS | StandardTraining
  INPUTSIZE: 32 # AutoFormer | OFA | DARTS | StandardTraining
  COLORJITTER: null # AutoFormer | OFA | DARTS | StandardTraining
  AA: null # AutoFormer | OFA | DARTS | StandardTraining
  TRAIN_INTERPOLATION: null # AutoFormer | OFA | DARTS | StandardTraining
  REPROB: 0. # AutoFormer | OFA | DARTS | StandardTraining
  REMODE: null # AutoFormer | OFA | DARTS | StandardTraining
  RECOUNT: null # AutoFormer | OFA | DARTS | StandardTraining
  CUTOUT: 16 # AutoFormer | OFA | DARTS | StandardTraining
  AUXWEIGHT: 0.4 # DARTS | StandardTraining
  LR: 0.025 # DARTS | StandardTraining
  MOMENTUM: 0.9 # DARTS | StandardTraining
  WEIGHTDECAY: 3e-4 # DARTS | StandardTraining
  EPOCHS: 3 # DARTS | StandardTraining default: 600
  DROPPATHPROB: 0.2 # DARTS | StandardTraining
  GRAD_CLIP: 5. # DARTS | StandardTraining
  TRAINPORTION: 0.9 # StandardTraining
OUTPUT: output
TAG: test