SEARCHSPACE:
  NAME: NAG
  GENERATOR: NAG # NAGMultiObj
  STATEDICTPATH: null # model_ckpts/NAG/generator.pkl # NAG model_ckpts/NAG/generator_multiobj.pkl
  PERFLABEL: 2 # NAG
  PARAMLABEL: 0 # NAG
SEARCHSTRATEGY:
  NAME: Random
  N: 10 # Random | AgingEvolution default: 1000
ESTIMATIONSTRATEGY:
  NAME: StandardTraining
  BATCHSIZE: 96 # AutoFormer | OFA | DARTS | StandardTraining default: 64
  DATASET: CIFAR10 # AutoFormer | OFA | DARTS | StandardTraining
  DATAPATH: datasets/cifar10 # AutoFormer | OFA | DARTS | StandardTraining
  INPUTSIZE: 32 # AutoFormer | OFA | DARTS | StandardTraining
  COLORJITTER: null # AutoFormer | OFA | DARTS | StandardTraining
  AA: null # AutoFormer | OFA | DARTS | StandardTraining
  TRAIN_INTERPOLATION: null # AutoFormer | OFA | DARTS | StandardTraining
  REPROB: 0. # AutoFormer | OFA | DARTS | StandardTraining
  REMODE: null # AutoFormer | OFA | DARTS | StandardTraining
  RECOUNT: null # AutoFormer | OFA | DARTS | StandardTraining
  CUTOUT: 16 # AutoFormer | OFA | DARTS | StandardTraining
  AUXWEIGHT: 0.4 # DARTS | StandardTraining
  LR: 0.025 # DARTS | StandardTraining
  MOMENTUM: 0.9 # DARTS | StandardTraining
  WEIGHTDECAY: 3e-4 # DARTS | StandardTraining
  EPOCHS: 3 # DARTS | StandardTraining default: 600
  DROPPATHPROB: 0.2 # DARTS | StandardTraining
  GRAD_CLIP: 5. # DARTS | StandardTraining
  TRAINPORTION: 0.9 # StandardTraining
OUTPUT: output
TAG: test
